---
- name: Install stow in Kali
  import_tasks: kali.yml
  when: ansible_distribution == "Kali"

- name: Remove files that will conflict with Stow
  loop:
    - .zshrc
    - .bashrc
    - .profile
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}//{{ item }}"
    state: absent

- name: Run stow
  shell: "stow stow_dir --target {{ ansible_env.HOME }} --verbose=2"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'
