---
- name: Install nvim build dependencies in Kali
  become: true
  apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
    state: present
  when: ansible_distribution == "Kali"

- name: Clean git repository
  become: true
  ansible.builtin.command:
    chdir: stow_dir/.local/bin/deps/neovim
    cmd: git clean -fdx
  changed_when: false

- name: Check if Neovim is installed
  ansible.builtin.command: nvim -v
  register: nvim
  ignore_errors: true
  changed_when: false

- name: Get VIMRUNTIME path
  shell:
    cmd: nvim --headless -c 'echo $VIMRUNTIME' -c quit
  register: nvim_vimruntime
  when: nvim.rc == 0
  changed_when: false

- name: Check if previous build exist
  ansible.builtin.stat:
    path: stow_dir/.local/bin/deps/neovim/build
  register: nvim_build

- name: Build nvim release version in Linux
  community.general.make:
    chdir: stow_dir/.local/bin/deps/neovim
    params:
      CMAKE_BUILD_TYPE: Release

- name: Uninstall previous installation of nvim
  become: true
  ansible.builtin.command:
    chdir: stow_dir/.local/bin/deps/neovim
    cmd: cmake --build build/ --target uninstall
  when: nvim_build.stat.exists

- name: Delete previous installation VIMRUNTIME path
  become: true
  file:
    path: "{{ nvim_vimruntime.stderr }}"
    state: absent
  when: nvim_runtime is defined

- name: Install nvim release version in Linux
  become: true
  community.general.make:
    chdir: stow_dir/.local/bin/deps/neovim
    target: install
